backend:
  name: git-gateway
  branch: main

media_folder: "src/assets"
public_folder: "../../assets"

collections:
  - name: "posts"
    label: "Inicio"
    folder: "src/content/docs"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "mdx"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Introducción", name: "intro", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
  
  - name: "Logotipos"
    label: "Logotipos"
    folder: "src/content/docs/logotipos"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "mdx"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }

  - name: "componentes"
    label: "Componentes"
    folder: "src/content/docs/componentes"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "mdx"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }

  - name: "fundamentos"
    label: "Fundamentos"
    folder: "src/content/docs/fundamentos"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "mdx"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
    